from enum import Enum
from typing import Annotated, List, Optional

from pydantic import BaseModel, Field

# TYPES & ENUMS

Year = Annotated[int, Field(ge=1900, le=2100)]
Month = Annotated[int, Field(ge=1, le=12)]


class EntityType(str, Enum):

    # INFECTIOUS DISEASE
    GASTROENTERITIS = "gastroenteritis"
    C_DIFFICILE_ENTEROCOLITIS = "c_difficile_enterocolitis"
    AMOEBIC_INFECTION = "amoebic_infection"
    AMOEBIC_LIVER_DISEASE = "amoebic_liver_disease"
    PULMONARY_TUBERCULOSIS = "pulmonary_tuberculosis"
    EXTRAPULMONARY_TUBERCULOSIS = "extrapulmonary_tuberculosis"
    MILIARY_TUBERCULOSIS = "miliary_tuberculosis"
    MENINGITIS = "meningitis"
    MENINGOCOCCAL_MENINGITIS = "meningococcal_meningitis"
    STREPTOCOCCAL_MENINGITIS = "streptococcal_meningitis"
    VIRAL_MENINGITIS = "viral_meningitis"
    ENCEPHALITIS = "encephalitis"
    VIRAL_ENCEPHALITIS = "viral_encephalitis"
    BRAIN_ABSCESS = "brain_abscess"
    SPINAL_ABSCESS = "spinal_abscess"
    LIVER_ABSCESS = "liver_abscess"
    DISCITIS = "discitis"
    OSTEOMYELITIS = "osteomyelitis"
    SEPSIS = "sepsis"
    MENINGOCOCCAL_SEPTICAEMIA = "meningococcal_septicaemia"
    STREPTOCOCCAL_SEPTICAEMIA = "streptococcal_septicaemia"
    STAPH_AUREUS_SEPTICAEMIA = "staph_aureus_septicaemia"
    GRAM_NEGATIVE_SEPTICAEMIA = "gram_negative_septicaemia"
    CATHETER_OR_LINE_RELATED_SEPTICAEMIA = "catheter_or_line_related_septicaemia"
    TOXIC_SHOCK_SYNDROME = "toxic_shock_syndrome"
    UPPER_RESPIRATORY_TRACT_INFECTION = "upper_respiratory_tract_infection"
    SINUSITIS = "sinusitis"
    PHARYNGITIS_OR_TONSILLITIS = "pharyngitis_or_tonsillitis"
    EPIGLOTTITIS = "epiglottitis"
    OROPHARYNGEAL_ABSCESS = "oropharyngeal_abscess"
    LUDWIGS_ANGINA = "ludwigs_angina"
    INFLUENZA = "influenza"
    LOWER_RESPIRATORY_TRACT_INFECTION = "lower_respiratory_tract_infection"
    PNEUMONIA = "pneumonia"
    COMMUNITY_ACQUIRED_PNEUMONIA = "community_acquired_pneumonia"
    HOSPITAL_ACQUIRED_PNEUMONIA = "hospital_acquired_pneumonia"
    ASPIRATION_PNEUMONIA = "aspiration_pneumonia"
    VIRAL_PNEUMONIA = "viral_pneumonia"
    LUNG_ABSCESS = "lung_abscess"
    LEGIONNAIRES_DISEASE = "legionnaires_disease"
    CELLULITIS = "cellulitis"
    CUTANEOUS_ABSCESS = "cutaneous_abscess"
    SURGICAL_WOUND_INFECTION = "surgical_wound_infection"
    NECROTISING_FASCIITIS = "necrotising_fasciitis"
    NEUROSYPHILIS = "neurosyphilis"
    LYME_DISEASE = "lyme_disease"
    HERPES_SIMPLEX_INFECTION = "herpes_simplex_infection"
    ECZEMA_HERPETICUM = "eczema_herpeticum"
    HERPES_ZOSTER_INFECTION = "herpes_zoster_infection"
    ACUTE_HEPATITIS_A = "acute_hepatitis_a"
    ACUTE_HEPATITIS_B = "acute_hepatitis_b"
    ACUTE_HEPATITIS_C = "acute_hepatitis_c"
    ACUTE_HEPATITIS_E = "acute_hepatitis_e"
    CHRONIC_HEPATITIS_B = "chronic_hepatitis_b"
    CHRONIC_HEPATITIS_C = "chronic_hepatitis_c"
    SYMPTOMATIC_HIV_DISEASE = "symptomatic_hiv_disease"
    CYTOMEGALOVIRAL_DISEASE = "cytomegaloviral_disease"
    INFECTIOUS_MONONUCLEOSIS = "infectious_mononucleosis"
    CANDIDIASIS = "candidiasis"
    CANDIDAL_SEPTICAEMIA = "candidal_septicaemia"
    ASPERGILLOSIS = "aspergillosis"
    INVASIVE_PULMONARY_ASPERGILLOSIS = "invasive_pulmonary_aspergillosis"
    PULMONARY_ASPERGILLOMA = "pulmonary_aspergilloma"
    PNEUMOCYSTIS_PNEUMONIA = "pneumocystis_pneumonia"
    MALARIA = "malaria"
    TOXOPLASMOSIS = "toxoplasmosis"
    GIARDIASIS = "giardiasis"
    CRYPTOSPORIDIOSIS = "cryptosporidiosis"
    SCABIES = "scabies"
    PERTUSSIS = "pertussis"
    VARICELLA = "varicella"
    MEASLES = "measles"
    CROUP = "croup"
    BRONCHIOLITIS = "bronchiolitis"
    SARS_INFECTION = "sars_infection"
    COVID_19_INFECTION = "covid_19_infection"
    POST_COVID_19_SYNDROME = "post_covid_19_syndrome"
    RESISTANCE_TO_BETA_LACTAM_ANTIBIOTICS = "resistance_to_beta_lactam_antibiotics"
    RESISTANCE_TO_OTHER_ANTIBIOTICS = "resistance_to_other_antibiotics"
    PYREXIA_OF_UNKNOWN_ORIGIN = "pyrexia_of_unknown_origin"

    # MALIGNANCIES
    PRIMARY_CANCER_LUNG = "primary_cancer_lung"
    PRIMARY_CANCER_BREAST = "primary_cancer_breast"
    PRIMARY_CANCER_COLORECTAL = "primary_cancer_colorectal"
    PRIMARY_CANCER_PROSTATE = "primary_cancer_prostate"
    PRIMARY_CANCER_SKIN = "primary_cancer_skin"
    PRIMARY_CANCER_PANCREAS = "primary_cancer_pancreas"
    PRIMARY_CANCER_LIVER_OR_BILIARY = "primary_cancer_liver_or_biliary"
    PRIMARY_CANCER_GI_UPPER = "primary_cancer_gi_upper"
    PRIMARY_CANCER_KIDNEY_OR_BLADDER = "primary_cancer_kidney_or_bladder"
    PRIMARY_CANCER_GYNAECOLOGICAL = "primary_cancer_gynaecological"
    PRIMARY_CANCER_TESTICULAR = "primary_cancer_testicular"
    PRIMARY_CANCER_BRAIN_OR_CNS = "primary_cancer_brain_or_cns"
    PRIMARY_CANCER_HEAD_AND_NECK = "primary_cancer_head_and_neck"
    PRIMARY_CANCER_HAEMATOLOGICAL = "primary_cancer_haematological"
    PRIMARY_CANCER_HODGKIN_LYMPHOMA = "primary_cancer_hodgkin_lymphoma"
    PRIMARY_CANCER_NON_HODGKIN_LYMPHOMA = "primary_cancer_non_hodgkin_lymphoma"
    PRIMARY_CANCER_ACUTE_LEUKAEMIA = "primary_cancer_acute_leukaemia"
    PRIMARY_CANCER_CHRONIC_LEUKAEMIA = "primary_cancer_chronic_leukaemia"
    PRIMARY_CANCER_MYELOMA = "primary_cancer_myeloma"
    CANCER_UNKNOWN_PRIMARY = "cancer_unknown_primary"
    KAPOSI_SARCOMA = "kaposi_sarcoma"
    CANCER_METASTASES = "cancer_metastases"
    BENIGN_NEOPLASM = "benign_neoplasm"
    EARLY_STAGE_NEOPLASM_IN_SITU = "early_stage_neoplasm_in_situ"

    # HAEMATOLOGICAL
    ANAEMIA = "anaemia"
    IRON_DEFICIENCY_ANAEMIA = "iron_deficiency_anaemia"
    PERNICIOUS_ANAEMIA = "pernicious_anaemia"
    ANAEMIA_OF_CHRONIC_DISEASE = "anaemia_of_chronic_disease"
    HAEMOLYTIC_ANAEMIA = "haemolytic_anaemia"
    APLASTIC_ANAEMIA = "aplastic_anaemia"
    SICKLE_CELL_TRAIT = "sickle_cell_trait"
    SICKLE_CELL_DISEASE = "sickle_cell_disease"
    THALASSAEMIA = "thalassaemia"
    HAEMOPHILIA = "haemophilia"
    THROMBOPHILIA = "thrombophilia"
    VON_WILLEBRAND_DISEASE = "von_willebrand_disease"
    THROMBOCYTOPENIA = "thrombocytopenia"
    IMMUNE_THROMBOCYTOPENIA = "immune_thrombocytopenia"
    HEPARIN_INDUCED_THROMBOCYTOPENIA = "heparin_induced_thrombocytopenia"
    DISSEMINATED_INTRAVASCULAR_COAGULATION = "disseminated_intravascular_coagulation"
    THROMBOTIC_THROMBOCYTOPENIC_PURPURA = "thrombotic_thrombocytopenic_purpura"
    HAEMOLYTIC_URAEMIC_SYNDROME = "haemolytic_uraemic_syndrome"
    ANTIPHOSPHOLIPID_SYNDROME = "antiphospholipid_syndrome"
    NEUTROPENIA = "neutropenia"
    FEBRILE_NEUTROPENIA = "febrile_neutropenia"
    AGRANULOCYTOSIS = "agranulocytosis"
    POLYCYTHAEMIA_VERA = "polycythaemia_vera"
    MYELODYSPLASTIC_SYNDROME = "myelodysplastic_syndrome"
    MYELOFIBROSIS = "myelofibrosis"
    MONOCLONAL_GAMMOPATHY_OF_UNDETERMINED_SIGNIFICANCE = "monoclonal_gammopathy_of_undetermined_significance"
    COMMON_VARIABLE_IMMUNODEFICIENCY = "common_variable_immunodeficiency"
    TUMOUR_LYSIS_SYNDROME = "tumour_lysis_syndrome"
    CYTOKINE_RELEASE_SYNDROME = "cytokine_release_syndrome"
    AMYLOIDOSIS = "amyloidosis"
    ANAPHYLAXIS = "anaphylaxis"
    ALLERGIC_REACTION_TO_DRUG = "allergic_reaction_to_drug"

    # ENDOCRINE
    HYPOTHYROIDISM = "hypothyroidism"
    MYXOEDEMA_COMA = "myxoedema_coma"
    HYPERTHYROIDISM = "hyperthyroidism"
    GRAVES_DISEASE = "graves_disease"
    THYROID_STORM = "thyroid_storm"
    THYROIDITIS = "thyroiditis"
    HASHIMOTOS_THYROIDITIS = "hashimotos_thyroiditis"
    SICK_EUTHYROID_SYNDROME = "sick_euthyroid_syndrome"
    DIABETES_MELLITUS = "diabetes_mellitus"
    TYPE_1_DIABETES_MELLITUS = "type_1_diabetes_mellitus"
    TYPE_2_DIABETES_MELLITUS = "type_2_diabetes_mellitus"
    DIABETIC_KETOACIDOSIS = "diabetic_ketoacidosis"
    HYPEROSMOLAR_HYPERGLYCAEMIC_STATE = "hyperosmolar_hyperglycaemic_state"
    DIABETIC_NEPHROPATHY = "diabetic_nephropathy"
    DIABETIC_RETINOPATHY = "diabetic_retinopathy"
    DIABETIC_PERIPHERAL_NEUROPATHY = "diabetic_peripheral_neuropathy"
    DIABETIC_AUTONOMIC_NEUROPATHY = "diabetic_autonomic_neuropathy"
    DIABETIC_ULCERS = "diabetic_ulcers"
    HYPOGLYCAEMIA = "hypoglycaemia"
    HYPOGLYCAEMIC_COMA = "hypoglycaemic_coma"
    HYPOPARATHYROIDISM = "hypoparathyroidism"
    HYPERPARATHYROIDISM = "hyperparathyroidism"
    ACROMEGALY = "acromegaly"
    HYPERPROLACTINAEMIA = "hyperprolactinaemia"
    SYNDROME_OF_INAPPROPRIATE_ADH = "syndrome_of_inappropriate_adh"
    HYPOPITUITARISM = "hypopituitarism"
    DIABETES_INSIPIDUS = "diabetes_insipidus"
    CUSHINGS_SYNDROME = "cushings_syndrome"
    HYPERALDOSTERONISM = "hyperaldosteronism"
    ADRENOCORTICAL_INSUFFICIENCY = "adrenocortical_insufficiency"
    ADDISONIAN_CRISIS = "addisonian_crisis"
    POLYCYSTIC_OVARIAN_SYNDROME = "polycystic_ovarian_syndrome"
    PRIMARY_OVARIAN_FAILURE = "primary_ovarian_failure"
    TESTICULAR_HYPOFUNCTION = "testicular_hypofunction"
    CARCINOID_SYNDROME = "carcinoid_syndrome"
    MALNUTRITION = "malnutrition"
    REFEEDING_SYNDROME = "refeeding_syndrome"
    WERNICKE_ENCEPHALOPATHY = "wernicke_encephalopathy"
    VITAMIN_D_DEFICIENCY = "vitamin_d_deficiency"
    IRON_DEFICIENCY = "iron_deficiency"
    OBESITY = "obesity"
    OBESITY_HYPOVENTILATION = "obesity_hypoventilation"
    HYPERLIPIDAEMIA = "hyperlipidaemia"
    HYPERNATRAEMIA = "hypernatraemia"
    HYPONATRAEMIA = "hyponatraemia"
    HYPERKALAEMIA = "hyperkalaemia"
    HYPOKALAEMIA = "hypokalaemia"
    HYPERCALCAEMIA = "hypercalcaemia"
    HYPOCALCAEMIA = "hypocalcaemia"
    VOLUME_DEPLETION = "volume_depletion"
    FLUID_OVERLOAD = "fluid_overload"
    LACTIC_ACIDOSIS = "lactic_acidosis"
    PHAEOCHROMOCYTOMA = "phaeochromocytoma"

    # DRUG / MENTAL DISORDERS
    ALCOHOL_USE_DISORDER = "alcohol_use_disorder"
    ALCOHOL_WITHDRAWAL = "alcohol_withdrawal"
    DELIRIUM_TREMENS = "delirium_tremens"
    OPIOID_USE_DISORDER = "opioid_use_disorder"
    OPIOID_WITHDRAWAL = "opioid_withdrawal"
    IV_DRUG_USE_DISORDER = "iv_drug_use_disorder"
    COCAINE_USE_DISORDER = "cocaine_use_disorder"
    CANNABIS_USE_DISORDER = "cannabis_use_disorder"
    PSYCHOTIC_EPISODE = "psychotic_episode"
    SCHIZOPHRENIA = "schizophrenia"
    SCHIZOAFFECTIVE_DISORDER = "schizoaffective_disorder"
    MANIC_EPISODE = "manic_episode"
    BIPOLAR_AFFECTIVE_DISORDER = "bipolar_affective_disorder"
    DEPRESSION = "depression"
    SUICIDAL_IDEATION = "suicidal_ideation"
    ANXIETY_DISORDER = "anxiety_disorder"
    POST_TRAUMATIC_STRESS_DISORDER = "post_traumatic_stress_disorder"
    ATTENTION_DEFICIT_HYPERACTIVITY_DISORDER = "attention_deficit_hyperactivity_disorder"
    ANOREXIA_NERVOSA = "anorexia_nervosa"
    BULIMIA_NERVOSA = "bulimia_nervosa"
    PERSONALITY_DISORDER = "personality_disorder"
    LEARNING_DISABILITY = "learning_disability"

    # NEUROLOGY
    DEMENTIA = "dementia"
    VASCULAR_DEMENTIA = "vascular_dementia"
    FRONTOTEMPORAL_DEMENTIA = "frontotemporal_dementia"
    LEWY_BODY_DEMENTIA = "lewy_body_dementia"
    MILD_COGNITIVE_IMPAIRMENT = "mild_cognitive_impairment"
    DELIRIUM = "delirium"
    HUNTINGTONS_DISEASE = "huntingtons_disease"
    HEREDITARY_ATAXIA = "hereditary_ataxia"
    MOTOR_NEURON_DISEASE = "motor_neuron_disease"
    PARANEOPLASTIC_NEUROLOGICAL_SYNDROME = "paraneoplastic_neurological_syndrome"
    PARKINSONS_DISEASE = "parkinsons_disease"
    SECONDARY_PARKINSONISM = "secondary_parkinsonism"
    NEUROLEPTIC_MALIGNANT_SYNDROME = "neuroleptic_malignant_syndrome"
    SEROTONIN_SYNDROME = "serotonin_syndrome"
    ESSENTIAL_TREMOR = "essential_tremor"
    ALZHEIMERS_DISEASE = "alzheimers_disease"
    EARLY_ONSET_ALZHEIMERS_DISEASE = "early_onset_alzheimers_disease"
    MULTIPLE_SCLEROSIS = "multiple_sclerosis"
    CENTRAL_PONTINE_MYELINOLYSIS = "central_pontine_myelinolysis"
    EPILEPSY = "epilepsy"
    STATUS_EPILEPTICUS = "status_epilepticus"
    MIGRAINE = "migraine"
    CLUSTER_HEADACHE_SYNDROME = "cluster_headache_syndrome"
    TRIGEMINAL_NEURALGIA = "trigeminal_neuralgia"
    BELLS_PALSY = "bells_palsy"
    SUBARACHNOID_HAEMORRHAGE = "subarachnoid_haemorrhage"
    CEREBRAL_ANEURYSM_NONRUPTURED = "cerebral_aneurysm_nonruptured"
    INTRACEREBRAL_HAEMORRHAGE = "intracerebral_haemorrhage"
    ISCHAEMIC_STROKE = "ischaemic_stroke"
    TRANSIENT_ISCHAEMIC_ATTACK = "transient_ischaemic_attack"
    CEREBRAL_VENOUS_SINUS_THROMBOSIS = "cerebral_venous_sinus_thrombosis"
    NERVE_ROOT_OR_PLEXUS_DISORDER = "nerve_root_or_plexus_disorder"
    GUILLAIN_BARRE_SYNDROME = "guillain_barre_syndrome"
    CHRONIC_INFLAMMATORY_DEMYELINATING_POLYNEUROPATHY = "chronic_inflammatory_demyelinating_polyneuropathy"
    PERIPHERAL_NEUROPATHY = "peripheral_neuropathy"
    MYASTHENIA_GRAVIS = "myasthenia_gravis"
    LAMBERT_EATON_SYNDROME = "lambert_eaton_syndrome"
    MUSCULAR_DYSTROPHY = "muscular_dystrophy"
    MYOPATHY = "myopathy"
    CRITICAL_ILLNESS_MYOPATHY = "critical_illness_myopathy"
    CEREBRAL_PALSY = "cerebral_palsy"
    HEMIPLEGIA = "hemiplegia"
    PARAPLEGIA_OR_TETRAPLEGIA = "paraplegia_or_tetraplegia"
    LOCKED_IN_SYNDROME = "locked_in_syndrome"
    HYDROCEPHALUS = "hydrocephalus"
    NORMAL_PRESSURE_HYDROCEPHALUS = "normal_pressure_hydrocephalus"
    RAISED_INTRACRANIAL_PRESSURE = "raised_intracranial_pressure"
    HYPOXIC_ANOXIC_BRAIN_INJURY = "hypoxic_anoxic_brain_injury"
    IDIOPATHIC_INTRACRANIAL_HYPERTENSION = "idiopathic_intracranial_hypertension"
    ENCEPHALOPATHY = "encephalopathy"
    POSTERIOR_REVERSIBLE_ENCEPHALOPATHY_SYNDROME = "posterior_reversible_encephalopathy_syndrome"
    COMPRESSION_OF_BRAIN = "compression_of_brain"
    CEREBRAL_OEDEMA = "cerebral_oedema"
    EXTRADURAL_HAEMORRHAGE = "extradural_haemorrhage"
    SUBDURAL_HAEMORRHAGE = "subdural_haemorrhage"
    SPINAL_CORD_COMPRESSION = "spinal_cord_compression"
    CAUDA_EQUINA_SYNDROME = "cauda_equina_syndrome"

    # OPHTHO/ENT
    CONJUNCTIVITIS = "conjunctivitis"
    DISORDERS_OF_SCLERA = "disorders_of_sclera"
    KERATITIS = "keratitis"
    UVEITIS = "uveitis"
    RETINAL_DETACHMENT = "retinal_detachment"
    CATARACT = "cataract"
    RETINAL_VASCULAR_OCCLUSIONS = "retinal_vascular_occlusions"
    RETINAL_HAEMORRHAGE = "retinal_haemorrhage"
    GLAUCOMA = "glaucoma"
    OPTIC_NEURITIS = "optic_neuritis"
    PAPILLOEDEMA = "papilloedema"
    VISUAL_IMPAIRMENT_INCLUDING_BLINDNESS = "visual_impairment_including_blindness"
    OTITIS_MEDIA = "otitis_media"
    MASTOIDITIS = "mastoiditis"
    VESTIBULAR_DISORDERS = "vestibular_disorders"
    HEARING_LOSS = "hearing_loss"
    MACULAR_DEGENERATION = "macular_degeneration"

    # CARDIOVASCULAR
    RHEUMATIC_FEVER = "rheumatic_fever"
    ESSENTIAL_HYPERTENSION = "essential_hypertension"
    HYPERTENSIVE_CARDIOMYOPATHY = "hypertensive_cardiomyopathy"
    HYPERTENSIVE_RENAL_DISEASE = "hypertensive_renal_disease"
    MALIGNANT_HYPERTENSION = "malignant_hypertension"
    HYPERTENSIVE_ENCEPHALOPATHY = "hypertensive_encephalopathy"
    SECONDARY_HYPERTENSION = "secondary_hypertension"
    ANGINA_PECTORIS = "angina_pectoris"
    STABLE_ANGINA = "stable_angina"
    UNSTABLE_ANGINA = "unstable_angina"
    ACUTE_MYOCARDIAL_INFARCTION = "acute_myocardial_infarction"
    SILENT_MYOCARDIAL_INFARCTION = "silent_myocardial_infarction"
    NON_ST_ELEVATION_MYOCARDIAL_INFARCTION = "non_st_elevation_myocardial_infarction"
    ST_ELEVATION_MYOCARDIAL_INFARCTION = "st_elevation_myocardial_infarction"
    CHRONIC_ISCHAEMIC_HEART_DISEASE = "chronic_ischaemic_heart_disease"
    DRESSLERS_SYNDROME = "dresslers_syndrome"
    ANEURYSM_OF_HEART = "aneurysm_of_heart"
    PULMONARY_EMBOLISM = "pulmonary_embolism"
    MASSIVE_PULMONARY_EMBOLISM = "massive_pulmonary_embolism"
    COR_PULMONALE = "cor_pulmonale"
    PRIMARY_PULMONARY_HYPERTENSION = "primary_pulmonary_hypertension"
    SECONDARY_PULMONARY_HYPERTENSION = "secondary_pulmonary_hypertension"
    PERICARDITIS = "pericarditis"
    RESTRICTIVE_PERICARDITIS = "restrictive_pericarditis"
    PERICARDIAL_EFFUSION = "pericardial_effusion"
    CARDIAC_TAMPONADE = "cardiac_tamponade"
    INFECTIVE_ENDOCARDITIS = "infective_endocarditis"
    MITRAL_VALVE_PROLAPSE = "mitral_valve_prolapse"
    MITRAL_REGURGITATION = "mitral_regurgitation"
    MITRAL_STENOSIS = "mitral_stenosis"
    AORTIC_REGURGITATION = "aortic_regurgitation"
    AORTIC_STENOSIS = "aortic_stenosis"
    TRICUSPID_REGURGITATION = "tricuspid_regurgitation"
    TRICUSPID_STENOSIS = "tricuspid_stenosis"
    PULMONARY_REGURGITATION = "pulmonary_regurgitation"
    PULMONARY_STENOSIS = "pulmonary_stenosis"
    MYOCARDITIS = "myocarditis"
    CARDIOMYOPATHY = "cardiomyopathy"
    DILATED_CARDIOMYOPATHY = "dilated_cardiomyopathy"
    HYPERTROPHIC_CARDIOMYOPATHY = "hypertrophic_cardiomyopathy"
    TAKOTSUBO_CARDIOMYOPATHY = "takotsubo_cardiomyopathy"
    SICK_SINUS_SYNDROME = "sick_sinus_syndrome"
    HEART_BLOCK = "heart_block"
    FIRST_DEGREE_HEART_BLOCK = "first_degree_heart_block"
    SECOND_DEGREE_HEART_BLOCK = "second_degree_heart_block"
    COMPLETE_HEART_BLOCK = "complete_heart_block"
    TRIFASCICULAR_BLOCK = "trifascicular_block"
    TACHYARRHYTHMIA = "tachyarrhythmia"
    SUPRAVENTRICULAR_TACHYCARDIA = "supraventricular_tachycardia"
    WOLFF_PARKINSON_WHITE_SYNDROME = "wolff_parkinson_white_syndrome"
    ATRIAL_FIBRILLATION = "atrial_fibrillation"
    PAROXYSMAL_ATRIAL_FIBRILLATION = "paroxysmal_atrial_fibrillation"
    ATRIAL_FLUTTER = "atrial_flutter"
    VENTRICULAR_ECTOPICS = "ventricular_ectopics"
    VENTRICULAR_TACHYCARDIA = "ventricular_tachycardia"
    VENTRICULAR_FIBRILLATION = "ventricular_fibrillation"
    CARDIAC_ARREST = "cardiac_arrest"
    CARDIAC_ARREST_WITH_ROSC = "cardiac_arrest_with_rosc"
    LONG_QT_SYNDROME = "long_qt_syndrome"
    BRUGADA_SYNDROME = "brugada_syndrome"
    PACEMAKER_IN_SITU = "pacemaker_in_situ"
    REPLACEMENT_HEART_VALVE_IN_SITU = "replacement_heart_valve_in_situ"
    IMPLANTABLE_CARDIOVERTER_DEFIBRILLATOR_IN_SITU = "implantable_cardioverter_defibrillator_in_situ"
    HEART_FAILURE = "heart_failure"
    LEFT_VENTRICULAR_FAILURE = "left_ventricular_failure"
    RIGHT_VENTRICULAR_FAILURE = "right_ventricular_failure"
    HEART_FAILURE_PRESERVED_EF = "heart_failure_preserved_ef"
    CARDIOMEGALY = "cardiomegaly"
    ATHEROSCLEROSIS = "atherosclerosis"
    CAROTID_ARTERY_STENOSIS = "carotid_artery_stenosis"
    RENAL_ARTERY_STENOSIS = "renal_artery_stenosis"
    PERIPHERAL_ARTERY_DISEASE = "peripheral_artery_disease"
    ACUTE_LIMB_ISCHAEMIA = "acute_limb_ischaemia"
    GANGRENE = "gangrene"
    MESENTERIC_ISCHAEMIA = "mesenteric_ischaemia"
    ISCHAEMIC_COLITIS = "ischaemic_colitis"
    AORTIC_DISSECTION = "aortic_dissection"
    AORTIC_ANEURYSM = "aortic_aneurysm"
    AORTIC_ANEURYSM_RUPTURE = "aortic_aneurysm_rupture"
    HEREDITARY_HAEMORRHAGIC_TELANGIECTASIA = "hereditary_haemorrhagic_telangiectasia"
    DEEP_VEIN_THROMBOSIS = "deep_vein_thrombosis"
    PERIPHERAL_VENOUS_INSUFFICIENCY = "peripheral_venous_insufficiency"
    LYMPHOEDEMA = "lymphoedema"
    HYPERTENSION = "hypertension"
    HYPOTENSION = "hypotension"
    ORTHOSTATIC_HYPOTENSION = "orthostatic_hypotension"
    DRUG_INDUCED_HYPOTENSION = "drug_induced_hypotension"
    POSTURAL_ORTHOSTATIC_TACHYCARDIA_SYNDROME = "postural_orthostatic_tachycardia_syndrome"

    # RESPIRATORY
    COPD = "copd"
    EMPHYSEMA = "emphysema"
    COPD_INFECTIVE_EXACERBATION = "copd_infective_exacerbation"
    COPD_NON_INFECTIVE_EXACERBATION = "copd_non_infective_exacerbation"
    ASTHMA = "asthma"
    STATUS_ASTHMATICUS = "status_asthmaticus"
    BRONCHIECTASIS = "bronchiectasis"
    BRONCHIECTASIS_INFECTIVE_EXACERBATION = "bronchiectasis_infective_exacerbation"
    CYSTIC_FIBROSIS = "cystic_fibrosis"
    CYSTIC_FIBROSIS_INFECTIVE_EXACERBATION = "cystic_fibrosis_infective_exacerbation"
    OCCUPATIONAL_LUNG_DISEASE = "occupational_lung_disease"
    ACUTE_RESPIRATORY_DISTRESS_SYNDROME = "acute_respiratory_distress_syndrome"
    PULMONARY_OEDEMA = "pulmonary_oedema"
    PULMONARY_HAEMORRHAGE = "pulmonary_haemorrhage"
    IDIOPATHIC_PULMONARY_FIBROSIS = "idiopathic_pulmonary_fibrosis"
    INTERSTITIAL_LUNG_DISEASE = "interstitial_lung_disease"
    PNEUMOTHORAX = "pneumothorax"
    TENSION_PNEUMOTHORAX = "tension_pneumothorax"
    PLEURAL_EFFUSION = "pleural_effusion"
    HAEMOTHORAX = "haemothorax"
    EMPYEMA = "empyema"
    TYPE_1_RESPIRATORY_FAILURE = "type_1_respiratory_failure"
    TYPE_2_RESPIRATORY_FAILURE = "type_2_respiratory_failure"
    RESPIRATORY_ARREST = "respiratory_arrest"
    SARCOIDOSIS = "sarcoidosis"
    OBSTRUCTIVE_SLEEP_APNOEA = "obstructive_sleep_apnoea"
    LONG_TERM_OXYGEN_THERAPY = "long_term_oxygen_therapy"

    # GI SYSTEM
    GASTRO_OESOPHAGEAL_REFLUX_DISEASE = "gastro_oesophageal_reflux_disease"
    OESOPHAGITIS = "oesophagitis"
    BARRETTS_OESOPHAGUS = "barretts_oesophagus"
    MALLORY_WEISS_TEAR = "mallory_weiss_tear"
    HIATUS_HERNIA = "hiatus_hernia"
    GASTRITIS_OR_DUODENITIS = "gastritis_or_duodenitis"
    GASTRIC_ULCER = "gastric_ulcer"
    DUODENAL_ULCER = "duodenal_ulcer"
    PERFORATED_UPPER_GI_ULCER = "perforated_upper_gi_ulcer"
    UPPER_GI_BLEED = "upper_gi_bleed"
    HAEMATEMESIS = "haematemesis"
    MELAENA = "melaena"
    LOWER_GI_BLEED = "lower_gi_bleed"
    ACUTE_APPENDICITIS = "acute_appendicitis"
    INGUINAL_OR_FEMORAL_HERNIA = "inguinal_or_femoral_hernia"
    UMBILICAL_HERNIA = "umbilical_hernia"
    VENTRAL_HERNIA = "ventral_hernia"
    CROHNS_DISEASE = "crohns_disease"
    ULCERATIVE_COLITIS = "ulcerative_colitis"
    COLITIS = "colitis"
    VOLVULUS = "volvulus"
    INTESTINAL_OBSTRUCTION = "intestinal_obstruction"
    ILEUS = "ileus"
    ACUTE_DIVERTICULITIS = "acute_diverticulitis"
    IRRITABLE_BOWEL_SYNDROME = "irritable_bowel_syndrome"
    MEGACOLON = "megacolon"
    BOWEL_PERFORATION = "bowel_perforation"
    PERITONITIS = "peritonitis"
    GILBERTS_SYNDROME = "gilberts_syndrome"
    FATTY_LIVER = "fatty_liver"
    ALCOHOLIC_FATTY_LIVER = "alcoholic_fatty_liver"
    ALCOHOLIC_LIVER_DISEASE = "alcoholic_liver_disease"
    ALCOHOLIC_HEPATITIS = "alcoholic_hepatitis"
    NON_ALCOHOLIC_STEATOHEPATITIS = "non_alcoholic_steatohepatitis"
    AUTOIMMUNE_HEPATITIS = "autoimmune_hepatitis"
    ACUTE_LIVER_FAILURE = "acute_liver_failure"
    SUBACUTE_LIVER_FAILURE = "subacute_liver_failure"
    HEPATIC_FIBROSIS = "hepatic_fibrosis"
    HEPATIC_CIRRHOSIS = "hepatic_cirrhosis"
    CHRONIC_LIVER_FAILURE = "chronic_liver_failure"
    PORTAL_HYPERTENSION = "portal_hypertension"
    HEPATIC_ENCEPHALOPATHY = "hepatic_encephalopathy"
    HEPATORENAL_SYNDROME = "hepatorenal_syndrome"
    PORTAL_VEIN_THROMBOSIS = "portal_vein_thrombosis"
    BUDD_CHIARI_SYNDROME = "budd_chiari_syndrome"
    VARICEAL_DISEASE = "variceal_disease"
    OESOPHAGEAL_VARICES = "oesophageal_varices"
    GASTRIC_VARICES = "gastric_varices"
    ACUTE_VARICEAL_BLEED = "acute_variceal_bleed"
    SPONTANEOUS_BACTERIAL_PERITONITIS = "spontaneous_bacterial_peritonitis"
    PRIMARY_BILIARY_CHOLANGITIS = "primary_biliary_cholangitis"
    PRIMARY_SCLEROSING_CHOLANGITIS = "primary_sclerosing_cholangitis"
    ALPHA_1_ANTITRYPSIN_DEFICIENCY = "alpha_1_antitrypsin_deficiency"
    WILSONS_DISEASE = "wilsons_disease"
    HAEMOCHROMATOSIS = "haemochromatosis"
    CHOLELITHIASIS = "cholelithiasis"
    CHOLECYSTITIS = "cholecystitis"
    CHOLANGITIS = "cholangitis"
    ACUTE_PANCREATITIS = "acute_pancreatitis"
    CHRONIC_PANCREATITIS = "chronic_pancreatitis"
    PANCREATIC_PSEUDOCYST = "pancreatic_pseudocyst"
    ACHALASIA = "achalasia"
    GASTROPARESIS = "gastroparesis"
    INTESTINAL_MALABSORPTION = "intestinal_malabsorption"
    COELIAC_DISEASE = "coeliac_disease"

    # DERMATOLOGY
    IMPETIGO = "impetigo"
    PEMPHIGUS = "pemphigus"
    PEMPHIGOID = "pemphigoid"
    ATOPIC_DERMATITIS = "atopic_dermatitis"
    PSORIASIS = "psoriasis"
    URTICARIA = "urticaria"
    ERYTHEMA_MULTIFORME = "erythema_multiforme"
    STEVENS_JOHNSON_SYNDROME = "stevens_johnson_syndrome"
    DRESS_SYNDROME = "dress_syndrome"
    TOXIC_EPIDERMAL_NECROLYSIS = "toxic_epidermal_necrolysis"
    ERYTHEMA_NODOSUM = "erythema_nodosum"
    PYODERMA_GANGRENOSUM = "pyoderma_gangrenosum"
    HIDRADENITIS_SUPPURATIVA = "hidradenitis_suppurativa"
    SKIN_ULCERATION = "skin_ulceration"
    PRESSURE_ULCER = "pressure_ulcer"
    VENOUS_ULCER = "venous_ulcer"
    ARTERIAL_ULCER = "arterial_ulcer"

    # RHEUM / MSK
    SEPTIC_ARTHRITIS = "septic_arthritis"
    PROSTHETIC_JOINT_INFECTION = "prosthetic_joint_infection"
    REACTIVE_ARTHROPATHY = "reactive_arthropathy"
    RHEUMATOID_ARTHRITIS = "rheumatoid_arthritis"
    PSORIATIC_OR_ENTEROPATHIC_ARTHROPATHY = "psoriatic_or_enteropathic_arthropathy"
    JUVENILE_ARTHRITIS = "juvenile_arthritis"
    GOUT = "gout"
    PSEUDOGOUT = "pseudogout"
    OSTEOARTHRITIS = "osteoarthritis"
    VASCULITIS = "vasculitis"
    POLYARTERITIS_NODOSA = "polyarteritis_nodosa"
    GRANULOMATOSIS_WITH_POLYANGIITIS = "granulomatosis_with_polyangiitis"
    TAKAYASU_ARTERITIS = "takayasu_arteritis"
    GIANT_CELL_ARTERITIS = "giant_cell_arteritis"
    POLYMYALGIA_RHEUMATICA = "polymyalgia_rheumatica"
    MICROSCOPIC_POLYANGIITIS = "microscopic_polyangiitis"
    POLYMYOSITIS = "polymyositis"
    DERMATOMYOSITIS = "dermatomyositis"
    SYSTEMIC_LUPUS_ERYTHEMATOSUS = "systemic_lupus_erythematosus"
    SYSTEMIC_SCLEROSIS = "systemic_sclerosis"
    SJOGRENS_SYNDROME = "sjogrens_syndrome"
    BEHCETS_DISEASE = "behcets_disease"
    RAYNAUDS_PHENOMENON = "raynauds_phenomenon"
    HYPERMOBILITY_SYNDROME = "hypermobility_syndrome"
    SCOLIOSIS = "scoliosis"
    ANKYLOSING_SPONDYLITIS = "ankylosing_spondylitis"
    SPONDYLOSIS = "spondylosis"
    SPINAL_STENOSIS = "spinal_stenosis"
    CERVICAL_DISC_DISORDER = "cervical_disc_disorder"
    SCIATICA = "sciatica"
    FIBROMYALGIA = "fibromyalgia"
    OSTEOPOROSIS = "osteoporosis"
    PATHOLOGICAL_FRACTURE = "pathological_fracture"
    RICKETS = "rickets"
    ADULT_OSTEOMALACIA = "adult_osteomalacia"
    OSTEONECROSIS = "osteonecrosis"
    PAGETS_DISEASE_OF_BONE = "pagets_disease_of_bone"
    CHRONIC_PAIN_SYNDROME = "chronic_pain_syndrome"

    # RENAL / GU
    NEPHROTIC_SYNDROME = "nephrotic_syndrome"
    NEPHRITIC_SYNDROME = "nephritic_syndrome"
    MICROSCOPIC_HAEMATURIA = "microscopic_haematuria"
    MACROSCOPIC_HAEMATURIA = "macroscopic_haematuria"
    GLOMERULONEPHRITIS = "glomerulonephritis"
    MINIMAL_CHANGE_DISEASE = "minimal_change_disease"
    MEMBRANOPROLIFERATIVE_GLOMERULONEPHRITIS = "membranoproliferative_glomerulonephritis"
    IGA_NEPHROPATHY = "iga_nephropathy"
    FOCAL_SEGMENTAL_GLOMERULOSCLEROSIS = "focal_segmental_glomerulosclerosis"
    ANTI_GBM_DISEASE = "anti_gbm_disease"
    AUTOSOMAL_DOMINANT_POLYCYSTIC_KIDNEY_DISEASE = "autosomal_dominant_polycystic_kidney_disease"
    RENAL_TUBULAR_ACIDOSIS = "renal_tubular_acidosis"
    ACUTE_TUBULAR_NECROSIS = "acute_tubular_necrosis"
    RHABDOMYOLYSIS = "rhabdomyolysis"
    TUBULOINTERSTITIAL_NEPHRITIS = "tubulointerstitial_nephritis"
    ACUTE_KIDNEY_INJURY = "acute_kidney_injury"
    ACUTE_RENAL_REPLACEMENT_THERAPY = "acute_renal_replacement_therapy"
    CHRONIC_KIDNEY_DISEASE = "chronic_kidney_disease"
    CKD_STAGE_3 = "ckd_stage_3"
    CKD_STAGE_4 = "ckd_stage_4"
    CKD_STAGE_5 = "ckd_stage_5"
    ARTERIOVENOUS_FISTULA_IN_SITU = "arteriovenous_fistula_in_situ"
    LONG_TERM_HAEMODIALYSIS = "long_term_haemodialysis"
    PERITONEAL_DIALYSIS = "peritoneal_dialysis"
    CONTRAST_INDUCED_NEPHROPATHY = "contrast_induced_nephropathy"
    UROLITHIASIS = "urolithiasis"
    RENAL_COLIC = "renal_colic"
    HYDRONEPHROSIS = "hydronephrosis"
    HYDROURETER = "hydroureter"
    NEPHROGENIC_DIABETES_INSIPIDUS = "nephrogenic_diabetes_insipidus"
    RENAL_ISCHAEMIA_OR_INFARCTION = "renal_ischaemia_or_infarction"
    URINARY_TRACT_INFECTION = "urinary_tract_infection"
    CYSTITIS = "cystitis"
    PYELONEPHRITIS = "pyelonephritis"
    UROSEPSIS = "urosepsis"
    BENIGN_PROSTATIC_HYPERPLASIA = "benign_prostatic_hyperplasia"
    PROSTATITIS = "prostatitis"
    TESTICULAR_TORSION = "testicular_torsion"
    FEMALE_PELVIC_INFLAMMATORY_DISEASE = "female_pelvic_inflammatory_disease"
    ENDOMETRIOSIS = "endometriosis"
    FIBROIDS = "fibroids"
    OVARIAN_TORSION = "ovarian_torsion"

    # PERINATAL
    ECTOPIC_PREGNANCY = "ectopic_pregnancy"
    PREGNANCY_WITH_ABORTIVE_OUTCOME = "pregnancy_with_abortive_outcome"
    PREGNANCY_SUCCESSFUL_DELIVERY = "pregnancy_successful_delivery"
    PREGNANCY_PRE_EXISTING_HYPERTENSION = "pregnancy_pre_existing_hypertension"
    GESTATIONAL_HYPERTENSION = "gestational_hypertension"
    PRE_ECLAMPSIA = "pre_eclampsia"
    HELLP_SYNDROME = "hellp_syndrome"
    ECLAMPSIA = "eclampsia"
    HYPEREMESIS_GRAVIDARUM = "hyperemesis_gravidarum"
    PREGNANCY_PRE_EXISTING_DIABETES = "pregnancy_pre_existing_diabetes"
    GESTATIONAL_DIABETES = "gestational_diabetes"

    # CONGENITAL
    TUBEROUS_SCLEROSIS = "tuberous_sclerosis"
    FETAL_ALCOHOL_SYNDROME = "fetal_alcohol_syndrome"
    MARFAN_SYNDROME = "marfan_syndrome"
    DOWN_SYNDROME = "down_syndrome"
    EDWARDS_SYNDROME = "edwards_syndrome"
    PATAU_SYNDROME = "patau_syndrome"
    TURNER_SYNDROME = "turner_syndrome"
    KLINEFELTER_SYNDROME = "klinefelter_syndrome"
    FRAGILE_X_SYNDROME = "fragile_x_syndrome"
    CONGENITAL_HEART_DISEASE = "congenital_heart_disease"
    EHLERS_DANLOS_SYNDROME = "ehlers_danlos_syndrome"

    # CLINICAL FINDINGS
    TACHYCARDIA = "tachycardia"
    BRADYCARDIA = "bradycardia"
    PALPITATIONS = "palpitations"
    DIAPHORESIS = "diaphoresis"
    NIGHT_SWEATS = "night_sweats"
    CYANOSIS = "cyanosis"
    PALLOR = "pallor"
    FLUSHING = "flushing"
    TACHYPNOEA = "tachypnoea"
    DYSPNOEA = "dyspnoea"
    EXERTIONAL_DYSPNOEA = "exertional_dyspnoea"
    ORTHOPNOEA = "orthopnoea"
    COUGH = "cough"
    PURULENT_SPUTUM = "purulent_sputum"
    EPISTAXIS = "epistaxis"
    HAEMOPTYSIS = "haemoptysis"
    STRIDOR = "stridor"
    WHEEZING = "wheezing"
    HYPOXIA = "hypoxia"
    VERTIGO = "vertigo"
    DIZZINESS = "dizziness"
    PRESYNCOPE = "presyncope"
    SYNCOPE_OR_ANY_COLLAPSE = "syncope_or_any_collapse"
    PYREXIA = "pyrexia"
    FEBRILE_CONVULSION = "febrile_convulsion"
    RIGORS = "rigors"
    SEIZURE = "seizure"
    LYMPHADENOPATHY = "lymphadenopathy"
    PERIPHERAL_OEDEMA = "peripheral_oedema"
    POLYDIPSIA = "polydipsia"
    CHEST_PAIN = "chest_pain"
    PLEURITIC_PAIN = "pleuritic_pain"
    ABDOMINAL_PAIN = "abdominal_pain"
    GUARDING_OR_PERITONISM = "guarding_or_peritonism"
    UPPER_ABDOMINAL_PAIN = "upper_abdominal_pain"
    LOWER_ABDOMINAL_PAIN = "lower_abdominal_pain"
    FLANK_PAIN = "flank_pain"
    LOWER_BACK_PAIN = "lower_back_pain"
    THORACIC_BACK_PAIN = "thoracic_back_pain"
    CHRONIC_BACK_PAIN = "chronic_back_pain"
    ARTHRALGIA = "arthralgia"
    MYALGIA = "myalgia"
    HEADACHE = "headache"
    MENINGISM = "meningism"
    PAIN = "pain"
    NEUROPATHIC_PAIN = "neuropathic_pain"
    SEVERE_PAIN = "severe_pain"
    CALF_PAIN_OR_SWELLING = "calf_pain_or_swelling"
    CLAUDICATION = "claudication"
    VOMITING = "vomiting"
    NAUSEA = "nausea"
    HEARTBURN = "heartburn"
    DYSPHAGIA = "dysphagia"
    CONSTIPATION = "constipation"
    DIARRHOEA = "diarrhoea"
    FAECAL_INCONTINENCE = "faecal_incontinence"
    JAUNDICE = "jaundice"
    ASCITES = "ascites"
    ABSENT_BOWEL_SOUNDS = "absent_bowel_sounds"
    ABSENT_FLATUS = "absent_flatus"
    CHANGE_IN_BOWEL_HABIT = "change_in_bowel_habit"
    SKIN_NUMBNESS = "skin_numbness"
    HYPERAESTHESIA = "hyperaesthesia"
    PRURITUS = "pruritus"
    TREMOR = "tremor"
    RIGIDITY = "rigidity"
    MUSCLE_CRAMP_OR_SPASM = "muscle_cramp_or_spasm"
    FASCICULATION = "fasciculation"
    ATAXIA = "ataxia"
    ATAXIC_GAIT = "ataxic_gait"
    PARALYTIC_GAIT = "paralytic_gait"
    DIFFICULTY_IN_WALKING = "difficulty_in_walking"
    IMMOBILITY = "immobility"
    FRAILTY = "frailty"
    RECURRENT_FALLS = "recurrent_falls"
    LOSS_OF_APPETITE = "loss_of_appetite"
    ABNORMAL_WEIGHT_LOSS = "abnormal_weight_loss"
    POOR_ORAL_INTAKE = "poor_oral_intake"
    CACHEXIA = "cachexia"
    DYSURIA = "dysuria"
    URINARY_INCONTINENCE = "urinary_incontinence"
    URINARY_RETENTION = "urinary_retention"
    ANURIA = "anuria"
    OLIGURIA = "oliguria"
    POLYURIA = "polyuria"
    CONFUSION_OR_DISORIENTATION = "confusion_or_disorientation"
    DROWSINESS = "drowsiness"
    STUPOR_DIFFICULT_TO_ROUSE = "stupor_difficult_to_rouse"
    AVPU_ALERT = "avpu_alert"
    AVPU_VOICE_RESPONSE = "avpu_voice_response"
    AVPU_PAIN_RESPONSE = "avpu_pain_response"
    AVPU_UNRESPONSIVE = "avpu_unresponsive"
    AUDITORY_HALLUCINATIONS = "auditory_hallucinations"
    VISUAL_HALLUCINATIONS = "visual_hallucinations"
    AGITATION = "agitation"
    ANGER = "anger"
    PHYSICAL_VIOLENCE = "physical_violence"
    POOR_PERSONAL_HYGIENE = "poor_personal_hygiene"
    COGNITIVE_DECLINE = "cognitive_decline"
    SPEECH_DISTURBANCE = "speech_disturbance"
    DYSPHASIA_OR_APHASIA = "dysphasia_or_aphasia"
    DYSARTHRIA = "dysarthria"
    ANOSMIA_OR_PAROSMIA = "anosmia_or_parosmia"
    JOINT_EFFUSION = "joint_effusion"
    NON_SPECIFIC_MALAISE = "non_specific_malaise"
    FATIGUE = "fatigue"
    GENERAL_WEAKNESS = "general_weakness"
    MUSCLE_WASTING = "muscle_wasting"
    HYPOTHERMIA = "hypothermia"
    WARM_WELL_PERFUSED = "warm_well_perfused"
    PERIARREST_STATE = "periarrest_state"

    # INJURY / POISONING
    ACUTE_FALL = "acute_fall"
    THORACIC_TRAUMA = "thoracic_trauma"
    ABDOMINAL_TRAUMA = "abdominal_trauma"
    INTRACRANIAL_TRAUMA = "intracranial_trauma"
    CONCUSSION = "concussion"
    FRACTURE_OF_SKULL_OR_FACIAL_BONES = "fracture_of_skull_or_facial_bones"
    FRACTURE_OF_CERVICAL_SPINE = "fracture_of_cervical_spine"
    FRACTURE_OF_THORACIC_SPINE = "fracture_of_thoracic_spine"
    FRACTURE_OF_RIB = "fracture_of_rib"
    FLAIL_CHEST = "flail_chest"
    FRACTURE_OF_LUMBAR_SPINE = "fracture_of_lumbar_spine"
    FRACTURE_OF_SHOULDER_OR_HUMERUS = "fracture_of_shoulder_or_humerus"
    FRACTURE_OF_FOREARM_WRIST_OR_HAND = "fracture_of_forearm_wrist_or_hand"
    FRACTURE_OF_PELVIS = "fracture_of_pelvis"
    FRACTURE_OF_HIP_OR_NECK_OF_FEMUR = "fracture_of_hip_or_neck_of_femur"
    FRACTURE_OF_FEMORAL_SHAFT = "fracture_of_femoral_shaft"
    FRACTURE_OF_LOWER_LEG_ANKLE_OR_FOOT = "fracture_of_lower_leg_ankle_or_foot"
    COMPARTMENT_SYNDROME = "compartment_syndrome"
    INTENTIONAL_SELF_HARM = "intentional_self_harm"
    INTENTIONAL_SELF_OVERDOSE = "intentional_self_overdose"
    NEGLECT = "neglect"
    PHYSICAL_ABUSE_OR_ASSAULT = "physical_abuse_or_assault"
    BURN_OR_SCALD_INJURY = "burn_or_scald_injury"
    DROWNING_OR_SUBMERSION_INJURY = "drowning_or_submersion_injury"
    MEDICATION_SIDE_EFFECT = "medication_side_effect"
    ACUTE_TOXICITY_FROM_MEDICATION = "acute_toxicity_from_medication"
    ACUTE_TOXICITY_FROM_PARACETAMOL = "acute_toxicity_from_paracetamol"
    ACUTE_ALCOHOL_INTOXICATION = "acute_alcohol_intoxication"
    ACUTE_OPIOID_INTOXICATION = "acute_opioid_intoxication"
    ACUTE_TOXICITY_FROM_COCAINE = "acute_toxicity_from_cocaine"
    ACUTE_TOXICITY_FROM_BENZODIAZEPINES = "acute_toxicity_from_benzodiazepines"
    ACUTE_TOXICITY_FROM_ANTIDEPRESSANTS = "acute_toxicity_from_antidepressants"
    CARBON_MONOXIDE_POISONING = "carbon_monoxide_poisoning"

    # RARE / METABOLIC
    FABRY_DISEASE = "fabry_disease"
    GAUCHER_DISEASE = "gaucher_disease"
    POMPE_DISEASE = "pompe_disease"
    MUCOPOLYSACCHARIDOSIS = "mucopolysaccharidosis"
    PORPHYRIA = "porphyria"
    GLYCOGEN_STORAGE_DISEASE = "glycogen_storage_disease"
    MITOCHONDRIAL_DISEASE = "mitochondrial_disease"

    # OTHER / SPECIALIST
    TRACHEOSTOMY_IN_SITU = "tracheostomy_in_situ"
    TRACHEOSTOMY_MALFUNCTION = "tracheostomy_malfunction"
    BI_LEVEL_POSITIVE_PRESSURE_VENTILATION = "bi_level_positive_pressure_ventilation"
    CONTINUOUS_POSITIVE_AIRWAY_PRESSURE = "continuous_positive_airway_pressure"
    INVASIVE_VENTILATION = "invasive_ventilation"
    PEG_IN_SITU = "peg_in_situ"
    TRANSPLANTED_KIDNEY = "transplanted_kidney"
    TRANSPLANTED_LIVER = "transplanted_liver"
    TRANSPLANTED_HEART = "transplanted_heart"
    TRANSPLANTED_STEM_CELLS = "transplanted_stem_cells"
    TRANSPLANT_FAILURE_OR_REJECTION = "transplant_failure_or_rejection"
    EXTRACORPOREAL_MEMBRANE_OXYGENATION = "extracorporeal_membrane_oxygenation"
    MULTIPLE_ORGAN_DYSFUNCTION_OR_FAILURE = "multiple_organ_dysfunction_or_failure"
    GRAFT_VERSUS_HOST_DISEASE = "graft_versus_host_disease"
    SYSTEMIC_INFLAMMATORY_RESPONSE_SYNDROME = "systemic_inflammatory_response_syndrome"
    CIRCULATORY_FAILURE = "circulatory_failure"
    CARDIOGENIC_SHOCK = "cardiogenic_shock"
    HYPOVOLAEMIC_SHOCK = "hypovolaemic_shock"
    DISTRIBUTIVE_SHOCK = "distributive_shock"
    MASSIVE_HAEMORRHAGE = "massive_haemorrhage"
    PALLIATIVE_CARE = "palliative_care"
    END_OF_LIFE_CARE = "end_of_life_care"

    # PROCEDURES
    EMERGENCY_SURGERY = "emergency_surgery"
    EMERGENCY_LAPAROTOMY = "emergency_laparotomy"
    MAJOR_OPEN_SURGERY = "major_open_surgery"
    MINIMALLY_INVASIVE_SURGERY = "minimally_invasive_surgery"
    ENDOSCOPIC_THERAPY = "endoscopic_therapy"
    PERCUTANEOUS_INTERVENTION = "percutaneous_intervention"
    ORGAN_TRANSPLANTATION = "organ_transplantation"
    CORONARY_ARTERY_BYPASS_GRAFT = "coronary_artery_bypass_graft"
    CORONARY_ARTERY_STENT = "coronary_artery_stent"
    CANCER_TUMOUR_RESECTION_OR_DEBULKING = "cancer_tumour_resection_or_debulking"
    MAJOR_UPPER_GI_SURGERY = "major_upper_gi_surgery"
    MAJOR_LOWER_GI_SURGERY = "major_lower_gi_surgery"
    MAJOR_HPB_SURGERY = "major_hpb_surgery"
    MAJOR_THORACIC_SURGERY = "major_thoracic_surgery"
    MAJOR_VASCULAR_SURGERY = "major_vascular_surgery"
    MAJOR_NEUROSURGERY = "major_neurosurgery"
    MAJOR_CARDIAC_SURGERY = "major_cardiac_surgery"
    MAJOR_ORTHOPAEDIC_SURGERY = "major_orthopaedic_surgery"
    MAJOR_UROLOGIC_SURGERY = "major_urologic_surgery"
    MAJOR_GYNAECOLOGIC_SURGERY = "major_gynaecologic_surgery"

    # SOCIAL
    SOCIAL_CARE_PACKAGE = "social_care_package"
    RESIDENTIAL_OR_CARE_HOME = "residential_or_care_home"
    NO_FIXED_ABODE = "no_fixed_abode"
    LIVING_ALONE_AT_HOME = "living_alone_at_home"
    LIVING_WITH_OTHERS_AT_HOME = "living_with_others_at_home"
    ZIMMER_OR_WALKER_DEPENDENCY = "zimmer_or_walker_dependency"
    WHEELCHAIR_DEPENDENCY = "wheelchair_dependency"
    ASSISTED_TRANSFER_BED_TO_CHAIR_DEPENDENCY = "assisted_transfer_bed_to_chair_dependency"
    BEDBOUND = "bedbound"
    UNEMPLOYED = "unemployed"
    ACTIVE_SMOKER = "active_smoker"
    EX_SMOKER = "ex_smoker"
    NEVER_SMOKED = "never_smoked"
    MEDICALLY_FIT_FOR_DISCHARGE = "medically_fit_for_discharge"
    DISCHARGE_PENDING_SOCIAL = "discharge_pending_social"
    DISCHARGE_PENDING_PLACEMENT = "discharge_pending_placement"
    DISCHARGE_PENDING_TRANSFER = "discharge_pending_transfer"

class EntityStatus(str, Enum):
    """
    Status of clinical entity relative to current encounter
    """

    CURRENT = "current"
    # Currently present or ongoing.
    # Use for: acute issues, active clinical findings, chronic conditions with on-going management, procedures in current episode.
    # Default for any present condition or finding.

    NEGATED = "negated"
    # Explicitly ruled out or denied.
    # Use for: "no chest pain", "biopsy negative", "patient denies fever" etc

    HYPOTHETICAL = "hypothetical"
    # Possible but unconfirmed.
    # Use for: differential diagnoses, "?PE", "consider", "cannot exclude", "query" etc

    HISTORICAL_EVENT = "historical_event"
    # Past occurrence of an acute event or procedure
    # Use for: "previous MI", "history of stroke", "CABG 2015" etc.
    # Applies to discrete occurrences

    RESOLVED_CONDITION = "resolved_condition"
    # Resolved chronic conditions that are no longer actively managed
    # Use for: "previous T2DM now off treatment", "cancer in remission" etc.

    FAMILY = "family"
    # Status refers to a family member
    # Use for: family history, children history in mother's notes

    OTHER = "other"
    # Status unclear or doesn't fit above.
    # Use for: scientific hypothetical discussions, where unclear
    # Use this also as a release valve where context is ambiguous


# MODELS

class Entity(BaseModel):
    entity: EntityType = Field(description="Entity")
    entity_name_source_text: str = Field(
        description="Verbatim text from document that maps to this entity"
    )
    entity_status: EntityStatus = Field(description="Status of clinical entity")
    entity_status_source_text: Optional[str] = Field(
        None, description="Verbatim text from which entity status is derived"
    )
    entity_severity_source_text: Optional[str] = Field(
        None, description="Verbatim text describing severity or intensity (e.g., mild, moderate, severe)"
    )
    entity_progress_source_text: Optional[str] = Field(
        None, description="Verbatim text describing change over time (e.g., worsening, improving, stable, unchanged)"
    )
    is_key_problem: bool = Field(
    description="TRUE if entity is of active relevance to current encounter (may overlap with other is_* fields)."
    )
    is_comorbidity: bool = Field(
        description="TRUE if entity is a chronic background condition (may overlap with is_key_problem)"
    )
    is_procedure: bool = Field(
        description="TRUE if entity is a procedure (may overlap with is_key_problem)"
    )
    diagnosis_or_occurrence_year: Optional[Year] = Field(
        None, description="Year of diagnosis or occurrence. Only if explicitly stated."
    )
    diagnosis_or_occurrence_month: Optional[Month] = Field(
        None, description="Month of diagnosis or occurrence. Only if explicitly stated."
    )
    is_new_diagnosis: bool = Field(
        description="TRUE if explicit declaration that this is a new or first diagnosis"
    )


class ContextSummary(BaseModel):
    doc_context: str = Field(
        description="Short description of document context (e.g. outpatient note, admission clerking, discharge summary, etc)"
    )
    doc_summary: str = Field(
        description="Short summary of document content, with focus on active issues"
    )


class EntitySchemaModel(BaseModel):
    is_clinical_document: bool = Field(
        description="TRUE if document contains patient clinical information"
    )
    has_active_malignancy: bool = Field(
        description="TRUE if patient has active cancer documented"
    )
    entities: Optional[List[Entity]] = None
    context_summary: Optional[ContextSummary] = None
    extraction_notes: Optional[str] = Field(
    None,
    description="Brief notes on extraction difficulties, ambiguities, or edge cases encountered"
)